### PR TITLE
Jj Saif new Storage implementation

### PR DESCRIPTION
**Pull request by teojunjie**
**Progress (JJ)** 
- Changed addressbookstorage to accept userPrefs instead of a single filepath, don't know if this is allowed but it does give us more flexibility in calling the different file paths by having access to userPrefs straight
- In-File to In-Memory transfer of models and data
 
**Progress (psyf) **
- Events created to handle in-memory to in-file transfer (working for Machines, Admins and Persons)
- UI element for indicating access-level
- Prepare ModelManager and StorageManager for Jobs

### CODE REVIEW

**Comment by Psyf** [comment]
can you pull my branch again? it's been reupdated. 
Also, since your code has my commits, should I be creating another PR?

What's the correct way of doing this?

**Comment by teojunjie** [comment]
image

I think this might be a good way of doing it. You can add my main repo in my account and then push to JJStorageBranch here

**Comment by Psyf** [comment]
If you're accessing userPrefs directly, please update diagram on devDocs before this PR is merged

**Comment by teojunjie** [comment]
> If you're accessing userPrefs directly, please update diagram on devDocs before this PR is merged

Noted have created an issue and will settle it before V1.4

**Pull request merged**
